on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          #flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter --version
      #- run: flutter upgrade
      - run: flutter pub get
      - run: flutter pub run flutter_app_name
      - run: flutter pub run flutter_launcher_icons:main
      #- run: flutter test
      - run: flutter build apk --target-platform=android-arm
      #- run: |
      #    flutter build ios --no-codesign
      #    cd build/ios/iphoneos
      #    mkdir Payload
      #    cd Payload
      #    ln -s ../Runner.app
      #    cd ..
      #    zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}






# push to master, main, develop
# pull request on main master
